/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDetailModal: typeof import('./../components/phone/AppDetailModal.vue')['default']
    AppGrid: typeof import('./../components/phone/AppGrid.vue')['default']
    AppIcon: typeof import('./../components/phone/AppIcon.vue')['default']
    Button: typeof import('./../components/ui/Button.vue')['default']
    DockBar: typeof import('./../components/phone/DockBar.vue')['default']
    DockModal: typeof import('./../components/phone/DockModal.vue')['default']
    ImageViewer: typeof import('./../components/ui/ImageViewer.vue')['default']
    PageIndicator: typeof import('./../components/phone/PageIndicator.vue')['default']
    PhoneFrame: typeof import('./../components/phone/PhoneFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./../components/phone/StatusBar.vue')['default']
    TechBadge: typeof import('./../components/phone/TechBadge.vue')['default']
    ThemeToggle: typeof import('./../components/ui/ThemeToggle.vue')['default']
  }
}
